//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Web {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Web() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Web", typeof(Web).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 发表评论 的本地化字符串。
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发表留言 的本地化字符串。
        /// </summary>
        public static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相册评论 的本地化字符串。
        /// </summary>
        public static string AlbumComments {
            get {
                return ResourceManager.GetString("AlbumComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相册 的本地化字符串。
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相册查看 的本地化字符串。
        /// </summary>
        public static string AlbumView {
            get {
                return ResourceManager.GetString("AlbumView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 归档 的本地化字符串。
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文章评论 的本地化字符串。
        /// </summary>
        public static string ArticleComments {
            get {
                return ResourceManager.GetString("ArticleComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文章 的本地化字符串。
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础信息 的本地化字符串。
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生日 的本地化字符串。
        /// </summary>
        public static string Birth {
            get {
                return ResourceManager.GetString("Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 by 的本地化字符串。
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新验证码 的本地化字符串。
        /// </summary>
        public static string ChangeValidationCode {
            get {
                return ResourceManager.GetString("ChangeValidationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐 的本地化字符串。
        /// </summary>
        public static string Commend {
            get {
                return ResourceManager.GetString("Commend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论 的本地化字符串。
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论回复提醒邮件 的本地化字符串。
        /// </summary>
        public static string CommentReplyEmail {
            get {
                return ResourceManager.GetString("CommentReplyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论 的本地化字符串。
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除评论 的本地化字符串。
        /// </summary>
        public static string DeleteComment {
            get {
                return ResourceManager.GetString("DeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除留言 的本地化字符串。
        /// </summary>
        public static string DeleteNote {
            get {
                return ResourceManager.GetString("DeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除选中项? 的本地化字符串。
        /// </summary>
        public static string DeleteTip_AreUSureDelete {
            get {
                return ResourceManager.GetString("DeleteTip_AreUSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不发送 的本地化字符串。
        /// </summary>
        public static string Donotsend {
            get {
                return ResourceManager.GetString("Donotsend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Facebook 的本地化字符串。
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In 的本地化字符串。
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简介 的本地化字符串。
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送回复提醒邮件 的本地化字符串。
        /// </summary>
        public static string IsSendEmail {
            get {
                return ResourceManager.GetString("IsSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-cn 的本地化字符串。
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新评论 的本地化字符串。
        /// </summary>
        public static string LatestComments {
            get {
                return ResourceManager.GetString("LatestComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表查看 的本地化字符串。
        /// </summary>
        public static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号信息 的本地化字符串。
        /// </summary>
        public static string LogOn_AccountInfo {
            get {
                return ResourceManager.GetString("LogOn_AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住我? 的本地化字符串。
        /// </summary>
        public static string LogOn_RememberMe {
            get {
                return ResourceManager.GetString("LogOn_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入您的用户名及密码，如果你还没有账号，请 的本地化字符串。
        /// </summary>
        public static string LogOn_Tip {
            get {
                return ResourceManager.GetString("LogOn_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码错误 的本地化字符串。
        /// </summary>
        public static string LogOn_UsernameOrPwdError {
            get {
                return ResourceManager.GetString("LogOn_UsernameOrPwdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登出 的本地化字符串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理 的本地化字符串。
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改信息 的本地化字符串。
        /// </summary>
        public static string ModifyInformation {
            get {
                return ResourceManager.GetString("ModifyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改用户信息 的本地化字符串。
        /// </summary>
        public static string ModifyUserInfo {
            get {
                return ResourceManager.GetString("ModifyUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须登录 的本地化字符串。
        /// </summary>
        public static string MustLogIn {
            get {
                return ResourceManager.GetString("MustLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的评论 的本地化字符串。
        /// </summary>
        public static string MyComments {
            get {
                return ResourceManager.GetString("MyComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的留言 的本地化字符串。
        /// </summary>
        public static string MyMessages {
            get {
                return ResourceManager.GetString("MyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新评论 的本地化字符串。
        /// </summary>
        public static string NewComments {
            get {
                return ResourceManager.GetString("NewComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称 的本地化字符串。
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有数据 的本地化字符串。
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有了 的本地化字符串。
        /// </summary>
        public static string NoMore {
            get {
                return ResourceManager.GetString("NoMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 留言 的本地化字符串。
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 留言回复提醒邮件 的本地化字符串。
        /// </summary>
        public static string NoteReplyEmail {
            get {
                return ResourceManager.GetString("NoteReplyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 留言 的本地化字符串。
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧密码 的本地化字符串。
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧密码错误 的本地化字符串。
        /// </summary>
        public static string OldPasswordWrong {
            get {
                return ResourceManager.GetString("OldPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 on 的本地化字符串。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 张 的本地化字符串。
        /// </summary>
        public static string OnePhoto {
            get {
                return ResourceManager.GetString("OnePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或者 的本地化字符串。
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请 的本地化字符串。
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发表于 的本地化字符串。
        /// </summary>
        public static string PostedOn {
            get {
                return ResourceManager.GetString("PostedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ 的本地化字符串。
        /// </summary>
        public static string Qq {
            get {
                return ResourceManager.GetString("Qq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Re 的本地化字符串。
        /// </summary>
        public static string Re {
            get {
                return ResourceManager.GetString("Re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新账号 的本地化字符串。
        /// </summary>
        public static string Register_CreateNewAccount {
            get {
                return ResourceManager.GetString("Register_CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用下面的表单创建账号,密码不能少于6个字符 的本地化字符串。
        /// </summary>
        public static string Register_Tip {
            get {
                return ResourceManager.GetString("Register_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名已存在, 请输入不同的用户名 的本地化字符串。
        /// </summary>
        public static string Register_UsernameExists {
            get {
                return ResourceManager.GetString("Register_UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复 的本地化字符串。
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置为默认 的本地化字符串。
        /// </summary>
        public static string RestoreDefault {
            get {
                return ResourceManager.GetString("RestoreDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文章 的本地化字符串。
        /// </summary>
        public static string Rss {
            get {
                return ResourceManager.GetString("Rss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索关键字 的本地化字符串。
        /// </summary>
        public static string SearchKey {
            get {
                return ResourceManager.GetString("SearchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 张 的本地化字符串。
        /// </summary>
        public static string SeveralPhotos {
            get {
                return ResourceManager.GetString("SeveralPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计 的本地化字符串。
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统错误 的本地化字符串。
        /// </summary>
        public static string SysError {
            get {
                return ResourceManager.GetString("SysError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板设置 的本地化字符串。
        /// </summary>
        public static string ThemeSetting {
            get {
                return ResourceManager.GetString("ThemeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条 的本地化字符串。
        /// </summary>
        public static string Tiao {
            get {
                return ResourceManager.GetString("Tiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码修改成功 的本地化字符串。
        /// </summary>
        public static string Tip_ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("Tip_ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该楼已经被删除 的本地化字符串。
        /// </summary>
        public static string Tip_ThisFloorBeenDeleted {
            get {
                return ResourceManager.GetString("Tip_ThisFloorBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置顶 的本地化字符串。
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论最多 的本地化字符串。
        /// </summary>
        public static string TopComments {
            get {
                return ResourceManager.GetString("TopComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览最多 的本地化字符串。
        /// </summary>
        public static string TopView {
            get {
                return ResourceManager.GetString("TopView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Twitter 的本地化字符串。
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传头像 的本地化字符串。
        /// </summary>
        public static string UploadAvatar {
            get {
                return ResourceManager.GetString("UploadAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人主页 的本地化字符串。
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户中心 的本地化字符串。
        /// </summary>
        public static string UserCenter {
            get {
                return ResourceManager.GetString("UserCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息 的本地化字符串。
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        public static string ValidationCode {
            get {
                return ResourceManager.GetString("ValidationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码输入错误 的本地化字符串。
        /// </summary>
        public static string ValidationCodeError {
            get {
                return ResourceManager.GetString("ValidationCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看详情 的本地化字符串。
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 踩 的本地化字符串。
        /// </summary>
        public static string Vote_Down {
            get {
                return ResourceManager.GetString("Vote_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投票成功 的本地化字符串。
        /// </summary>
        public static string Vote_Tip_Success {
            get {
                return ResourceManager.GetString("Vote_Tip_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已经投过票 的本地化字符串。
        /// </summary>
        public static string Vote_Tip_Voted {
            get {
                return ResourceManager.GetString("Vote_Tip_Voted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶 的本地化字符串。
        /// </summary>
        public static string Vote_Up {
            get {
                return ResourceManager.GetString("Vote_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微薄 的本地化字符串。
        /// </summary>
        public static string Weibo {
            get {
                return ResourceManager.GetString("Weibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年 的本地化字符串。
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
